# Generated by Django 4.1 on 2024-07-11 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('machinelearn', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
