# Generated by Django 4.1 on 2024-07-13 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('machinelearn', '0002_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='rback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=11, null=True, verbose_name='用户名')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='邮箱')),
                ('niming', models.SmallIntegerField(choices=[(1, '是'), (2, '否')], verbose_name='是否匿名')),
                ('content', models.TextField(verbose_name='反馈内容')),
            ],
        ),
    ]
