# Generated by Django 4.1 on 2024-07-15 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machinelearn', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='histy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64, verbose_name='用户名')),
                ('usetime', models.DateTimeField(verbose_name='使用时间')),
                ('usecontent', models.TextField(verbose_name='工作记录')),
            ],
        ),
        migrations.AlterField(
            model_name='rback',
            name='content',
            field=models.TextField(verbose_name='讨论或反馈内容'),
        ),
        migrations.AlterField(
            model_name='rback',
            name='username',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='用户名'),
        ),
    ]
